apiVersion: v1
kind: PersistentVolume
metadata:
  name: gogs-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100Mi
  glusterfs:
    endpoints: glusterfs-cluster
    path: k8s-volume
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gogs-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

