apiVersion: v1
kind: Service
metadata:
  name: gogs
spec:
  ports:
  - port: 80
    targetPort: 3000
  type: NodePort
  selector:
    app: gogs
---
apiVersion: v1
kind: Service
metadata:
  name: gogs-ssh
spec:
  ports:
  - port: 22
    targetPort: 22
  type: NodePort
  selector:
    app: gogs-ssh

